const fs=require("fs"); const path=require("path"); const { garantirArquivo }=require("./dadosPersistentes.service");
const pizzasPath=garantirArquivo("precospizzas.json","data/precospizzas.json",{}), bebidasPath=garantirArquivo("precosbebidas.json","data/precosbebidas.json",{}), promosPath=garantirArquivo("promocoes.json",null,{pizzas:{},bebidas:{}}), nomesPath=garantirArquivo("nomesbebidas.json","data/nomesbebidas.json",{}), ingredientesPath=garantirArquivo("ingredientespizzas.json",null,{});
const ler=(p,d)=>{try{return JSON.parse(fs.readFileSync(p,"utf8"))}catch{return d}}, salvar=(p,d)=>fs.writeFileSync(p,JSON.stringify(d,null,2),"utf8"), valido=v=>Number.isFinite(Number(v))&&Number(v)>=.01&&Number(v)<=5000, n=v=>Number(Number(v).toFixed(2));
function catalogo(){return {pizzas:ler(pizzasPath,{}),bebidas:ler(bebidasPath,{}),nomesBebidas:ler(nomesPath,{}),ingredientesPizzas:ler(ingredientesPath,{}),promocoes:ler(promosPath,{pizzas:{},bebidas:{}})}}
function ativa(p){return Boolean(p&&p.ativa!==false&&valido(p.por))}
function obterPrecosPizzas(){const c=catalogo();return Object.fromEntries(Object.entries(c.pizzas).map(([nome,t])=>[nome,Object.fromEntries(Object.entries(t).map(([tam,v])=>[tam,ativa(c.promocoes.pizzas?.[nome]?.[tam])?n(c.promocoes.pizzas[nome][tam].por):Number(v)]))]))}
function obterPrecosBebidas(){const c=catalogo();return Object.fromEntries(Object.entries(c.bebidas).map(([k,v])=>[k,ativa(c.promocoes.bebidas?.[k])?n(c.promocoes.bebidas[k].por):Number(v)]))}
function atualizarPrecoPizza(nome,tamanho,preco){const d=ler(pizzasPath,{});if(!d[nome]||!(tamanho in d[nome]))throw Error("Pizza ou tamanho não encontrado.");if(!valido(preco))throw Error("Informe um preço entre R$ 0,01 e R$ 5.000,00.");d[nome][tamanho]=n(preco);salvar(pizzasPath,d);return d[nome][tamanho]}
function atualizarIngredientesPizza(nome,ingredientes){const pizzas=ler(pizzasPath,{}),texto=String(ingredientes||"").trim();if(!pizzas[nome])throw Error("Pizza não encontrada.");if(!texto||texto.length>500)throw Error("Informe os ingredientes (até 500 caracteres).");const d=ler(ingredientesPath,{});d[nome]=texto;salvar(ingredientesPath,d);return texto}
function atualizarPrecoBebida(chave,preco){const d=ler(bebidasPath,{});if(!(chave in d))throw Error("Bebida não encontrada.");if(!valido(preco))throw Error("Informe um preço entre R$ 0,01 e R$ 5.000,00.");d[chave]=n(preco);salvar(bebidasPath,d);return d[chave]}
function salvarPromocao({tipo,chave,tamanho,nome,de,por,ativa=true}){const c=catalogo(), titulo=String(nome||"").trim();if(!["pizza","bebida"].includes(tipo))throw Error("Tipo inválido.");if(!titulo||titulo.length>80)throw Error("Informe o nome da promoção (até 80 caracteres).");if(!valido(de)||!valido(por)||Number(por)>=Number(de))throw Error("O valor 'por' deve ser menor que o valor 'de'.");if(tipo==="pizza"){if(!c.pizzas[chave]||!(tamanho in c.pizzas[chave]))throw Error("Pizza ou tamanho não encontrado.");c.pizzas[chave][tamanho]=n(de);salvar(pizzasPath,c.pizzas);c.promocoes.pizzas[chave]||={};c.promocoes.pizzas[chave][tamanho]={nome:titulo,de:n(de),por:n(por),ativa:Boolean(ativa)}}else{if(!(chave in c.bebidas))throw Error("Bebida não encontrada.");c.bebidas[chave]=n(de);salvar(bebidasPath,c.bebidas);c.promocoes.bebidas[chave]={nome:titulo,de:n(de),por:n(por),ativa:Boolean(ativa)}}salvar(promosPath,c.promocoes);return c.promocoes}
function removerPromocao(tipo,chave,tamanho){const p=catalogo().promocoes;if(tipo==="pizza"){delete p.pizzas?.[chave]?.[tamanho];if(p.pizzas?.[chave]&&!Object.keys(p.pizzas[chave]).length)delete p.pizzas[chave]}else if(tipo==="bebida")delete p.bebidas?.[chave];else throw Error("Tipo inválido.");salvar(promosPath,p);return p}
module.exports={catalogo,ativa,obterPrecosPizzas,obterPrecosBebidas,atualizarPrecoPizza,atualizarIngredientesPizza,atualizarPrecoBebida,salvarPromocao,removerPromocao};

